Mount Colab to drive

In [2]:
# Connect colab to drive
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
!ls "/content/drive/MyDrive/Project"

cif_files    testing.pt   Untitled0.ipynb  validating.pt
Dataset.csv  training.pt  Untitled1.ipynb

Install required libraries

In [4]:
# Install required libraries for crystal GNN
# Install necessary packages
!pip install torch torchvision torchaudio
!pip install torch-geometric
!pip install network
!pip install torch-geometric torch-scatter torch-sparse   # PyG (requires matching PyTorch version)
!pip install pymatgen ase                                # For parsing CIFs
!pip install deepchem                                    # For MEGNet
!pip install pysr                                        # Symbolic Regression
!pip install shap                                       # SHAP explainability
!pip install scikit-learn                               # Data splitting metrics

Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cpu)
Requirement already satisfied: torchvision in /usr/local/lib/python3.12/dist-packages (0.25.0+cpu)
Requirement already satisfied: torchaudio in /usr/local/lib/python3.12/dist-packages (2.10.0+cpu)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.25.1)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torchvision) (2.0.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision) (11.3.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Collecting torch-geometric
  Downloading torch_geometric-2.7.0-py3-none-any.whl.metadata (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.7/63.7 kB 2.3 MB/s eta 0:00:00
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (3.13.3)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (2025.3.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (3.1.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (2.0.2)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (5.9.5)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (3.3.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (3.6.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (1.23.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch-geometric) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->torch-geometric) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->torch-geometric) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->torch-geometric) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->torch-geometric) (2026.2.25)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.12/dist-packages (from aiosignal>=1.4.0->aiohttp->torch-geometric) (4.15.0)
Downloading torch_geometric-2.7.0-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 23.9 MB/s eta 0:00:00
Installing collected packages: torch-geometric
Successfully installed torch-geometric-2.7.0
Collecting network
  Downloading network-0.1.tar.gz (2.8 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: network
  Building wheel for network (setup.py) ... done
  Created wheel for network: filename=network-0.1-py3-none-any.whl size=3138 sha256=f2cf441cd80af3db9faacefeb603de265ed3c089123e80cecd453510ef9fca24
  Stored in directory: /root/.cache/pip/wheels/e7/5a/7a/7f15bea66afb5505b9d10cc7bd8964cb77f0ce736df5b104c8
Successfully built network
Installing collected packages: network
Successfully installed network-0.1
Requirement already satisfied: torch-geometric in /usr/local/lib/python3.12/dist-packages (2.7.0)
Collecting torch-scatter
  Downloading torch_scatter-2.1.2.tar.gz (108 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.0/108.0 kB 3.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting torch-sparse
  Downloading torch_sparse-0.6.18.tar.gz (209 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 210.0/210.0 kB 9.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (3.13.3)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (2025.3.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (3.1.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (2.0.2)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (5.9.5)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (3.3.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (3.6.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from torch-sparse) (1.16.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (1.23.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch-geometric) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->torch-geometric) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->torch-geometric) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->torch-geometric) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->torch-geometric) (2026.2.25)
Requirement already satisfied: typing-extensions>=4.2 in /usr/local/lib/python3.12/dist-packages (from aiosignal>=1.4.0->aiohttp->torch-geometric) (4.15.0)
Building wheels for collected packages: torch-scatter, torch-sparse
  Building wheel for torch-scatter (setup.py) ... done
  Created wheel for torch-scatter: filename=torch_scatter-2.1.2-cp312-cp312-linux_x86_64.whl size=677287 sha256=9ef900d880f1878b81383286341c7439243bd2d4ec20eb2ef728fb625a370894
  Stored in directory: /root/.cache/pip/wheels/84/20/50/44800723f57cd798630e77b3ec83bc80bd26a1e3dc3a672ef5
  Building wheel for torch-sparse (setup.py) ... done
  Created wheel for torch-sparse: filename=torch_sparse-0.6.18-cp312-cp312-linux_x86_64.whl size=1261482 sha256=08211b4d1a9ed66b19017f8b627f7b20e8c218e2270553c277f4ef749d9b5af9
  Stored in directory: /root/.cache/pip/wheels/71/fa/21/bd1d78ce1629aec4ecc924a63b82f6949dda484b6321eac6f2
Successfully built torch-scatter torch-sparse
Installing collected packages: torch-scatter, torch-sparse
Successfully installed torch-scatter-2.1.2 torch-sparse-0.6.18
Collecting pymatgen
  Downloading pymatgen-2025.10.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting ase
  Downloading ase-3.27.0-py3-none-any.whl.metadata (4.3 kB)
Collecting bibtexparser>=1.4.0 (from pymatgen)
  Downloading bibtexparser-1.4.4.tar.gz (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.6/55.6 kB 2.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: joblib>=1 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (1.5.3)
Requirement already satisfied: matplotlib>=3.8 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (3.10.0)
Collecting monty>=2025.1.9 (from pymatgen)
  Downloading monty-2026.2.18-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: networkx>=2.7 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (3.6.1)
Requirement already satisfied: numpy<3,>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (2.0.2)
Requirement already satisfied: orjson<4,>=3.10 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (3.11.7)
Collecting palettable>=3.3.3 (from pymatgen)
  Downloading palettable-3.3.3-py2.py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: pandas>=2 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (2.2.2)
Requirement already satisfied: plotly>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (5.24.1)
Requirement already satisfied: requests>=2.30 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (2.32.4)
Collecting ruamel.yaml>=0.17.0 (from pymatgen)
  Downloading ruamel_yaml-0.19.1-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: scipy>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (1.16.3)
Collecting spglib>=2.5 (from pymatgen)
  Downloading spglib-2.7.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (4.2 kB)
Requirement already satisfied: sympy>=1.3 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (1.14.0)
Requirement already satisfied: tabulate>=0.9 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (0.9.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from pymatgen) (4.67.3)
Collecting uncertainties>=3.1.4 (from pymatgen)
  Downloading uncertainties-3.2.3-py3-none-any.whl.metadata (7.0 kB)
Requirement already satisfied: pyparsing>=2.0.3 in /usr/local/lib/python3.12/dist-packages (from bibtexparser>=1.4.0->pymatgen) (3.3.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->pymatgen) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->pymatgen) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->pymatgen) (4.62.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->pymatgen) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->pymatgen) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->pymatgen) (11.3.0)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.8->pymatgen) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=2->pymatgen) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=2->pymatgen) (2025.3)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=5.0.0->pymatgen) (9.1.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30->pymatgen) (3.4.5)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30->pymatgen) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30->pymatgen) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30->pymatgen) (2026.2.25)
Requirement already satisfied: typing-extensions>=4.9.0 in /usr/local/lib/python3.12/dist-packages (from spglib>=2.5->pymatgen) (4.15.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.3->pymatgen) (1.3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.8->pymatgen) (1.17.0)
Downloading pymatgen-2025.10.7-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (4.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 52.4 MB/s eta 0:00:00
Downloading ase-3.27.0-py3-none-any.whl (2.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 95.1 MB/s eta 0:00:00
Downloading monty-2026.2.18-py3-none-any.whl (52 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.7/52.7 kB 4.2 MB/s eta 0:00:00
Downloading palettable-3.3.3-py2.py3-none-any.whl (332 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 332.3/332.3 kB 24.4 MB/s eta 0:00:00
Downloading ruamel_yaml-0.19.1-py3-none-any.whl (118 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.1/118.1 kB 10.2 MB/s eta 0:00:00
Downloading spglib-2.7.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (962 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 962.5/962.5 kB 56.5 MB/s eta 0:00:00
Downloading uncertainties-3.2.3-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.1/60.1 kB 4.8 MB/s eta 0:00:00
Building wheels for collected packages: bibtexparser
  Building wheel for bibtexparser (setup.py) ... done
  Created wheel for bibtexparser: filename=bibtexparser-1.4.4-py3-none-any.whl size=43609 sha256=6be141707b068a413f525673faecf7625a59f62629451989269e924e3d3afb87
  Stored in directory: /root/.cache/pip/wheels/54/f8/e6/ecfceb6af875ddc5096bb3811795ac336f50371009a601454d
Successfully built bibtexparser
Installing collected packages: uncertainties, spglib, ruamel.yaml, palettable, bibtexparser, monty, pymatgen, ase
Successfully installed ase-3.27.0 bibtexparser-1.4.4 monty-2026.2.18 palettable-3.3.3 pymatgen-2025.10.7 ruamel.yaml-0.19.1 spglib-2.7.0 uncertainties-3.2.3
Collecting deepchem
  Downloading deepchem-2.5.0-py3-none-any.whl.metadata (1.1 kB)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from deepchem) (1.5.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from deepchem) (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from deepchem) (2.2.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from deepchem) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from deepchem) (1.16.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->deepchem) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->deepchem) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->deepchem) (2025.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->deepchem) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->deepchem) (1.17.0)
Downloading deepchem-2.5.0-py3-none-any.whl (552 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 552.4/552.4 kB 10.5 MB/s eta 0:00:00
Installing collected packages: deepchem
Successfully installed deepchem-2.5.0
Collecting pysr
  Downloading pysr-1.5.9-py3-none-any.whl.metadata (54 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 2.7 MB/s eta 0:00:00
Requirement already satisfied: click<9.0.0,>=7.0.0 in /usr/local/lib/python3.12/dist-packages (from pysr) (8.3.1)
Collecting juliacall<0.9.27,>=0.9.24 (from pysr)
  Downloading juliacall-0.9.26-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: numpy<3.0.0,>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from pysr) (2.0.2)
Requirement already satisfied: pandas<3.0.0,>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pysr) (2.2.2)
Requirement already satisfied: scikit-learn<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from pysr) (1.6.1)
Requirement already satisfied: sympy<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from pysr) (1.14.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from pysr) (4.15.0)
Collecting juliapkg<0.2,>=0.1.17 (from juliacall<0.9.27,>=0.9.24->pysr)
  Downloading juliapkg-0.1.23-py3-none-any.whl.metadata (6.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=0.21.0->pysr) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=0.21.0->pysr) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=0.21.0->pysr) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=1.0.0->pysr) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=1.0.0->pysr) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2.0.0,>=1.0.0->pysr) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy<2.0.0,>=1.0.0->pysr) (1.3.0)
Requirement already satisfied: filelock<4.0,>=3.16 in /usr/local/lib/python3.12/dist-packages (from juliapkg<0.2,>=0.1.17->juliacall<0.9.27,>=0.9.24->pysr) (3.25.1)
Collecting semver<4.0,>=3.0 (from juliapkg<0.2,>=0.1.17->juliacall<0.9.27,>=0.9.24->pysr)
  Downloading semver-3.0.4-py3-none-any.whl.metadata (6.8 kB)

Import libraries

In [ ]:
import os
import numpy as np
import pandas as pd

from pymatgen.core import Structure

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch_geometric.data import Data
from torch_geometric.loader import DataLoader
from torch_geometric.nn import CGConv, global_mean_pool

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, classification_report

import warnings
warnings.filterwarnings("ignore")

Load Data

In [ ]:
data_df = "/content/drive/MyDrive/Project/Dataset.csv"

df = pd.read_csv(data_df)

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (7000, 17)

,mp_material_id,mp_formula,spacegroup,spacegroup_number,number of atoms,Band Gap,a,b,c,alpha,beta,gamma,Z,electronegativity,Topological Label,label,cif
0,mp-331,ScAl,Pm3m,221,2.0,0.0000,3.370349,3.370349,3.370349,90.000000,90.000000,90.000000,1.0,1.485,TI,1,cif_files/mp-331.cif
1,mp-698479,RbTeHOF4,Cc,9,32.0,4.8825,8.430517,8.430517,14.075609,85.886490,85.886490,34.382176,6.4,3.060,Trivial,0,cif_files/mp-698479.cif
2,mp-549237,Sr2Fe2S2OF2,I4/mmm,139,18.0,1.4677,4.095118,4.096245,18.221803,90.002343,90.003680,89.993481,3.6,2.458,Trivial,0,cif_files/mp-549237.cif
3,mp-13089,Cu2SnTe3,Imm2,44,6.0,0.0000,4.409910,6.113668,7.554224,113.869340,106.970766,90.000000,1.0,2.010,Trivial,0,cif_files/mp-13089.cif
4,mp-10732,ThTaN3,Pm-3m,221,5.0,0.0766,4.064437,4.064437,4.064437,90.000000,90.000000,90.000000,1.0,2.384,Topological,1,cif_files/mp-10732.cif

Feature selection

In [ ]:
#selection of features
df_data = df[[
    "spacegroup",
    "spacegroup_number",
    "number of atoms",
    "Band Gap",
    "a","b","c",
    "alpha","beta","gamma",
    "Z",
    "electronegativity",
    "label",
    "cif"
]].copy()

df_data.head()

,spacegroup,spacegroup_number,number of atoms,Band Gap,a,b,c,alpha,beta,gamma,Z,electronegativity,label,cif
0,Pm3m,221,2.0,0.0000,3.370349,3.370349,3.370349,90.000000,90.000000,90.000000,1.0,1.485,1,cif_files/mp-331.cif
1,Cc,9,32.0,4.8825,8.430517,8.430517,14.075609,85.886490,85.886490,34.382176,6.4,3.060,0,cif_files/mp-698479.cif
2,I4/mmm,139,18.0,1.4677,4.095118,4.096245,18.221803,90.002343,90.003680,89.993481,3.6,2.458,0,cif_files/mp-549237.cif
3,Imm2,44,6.0,0.0000,4.409910,6.113668,7.554224,113.869340,106.970766,90.000000,1.0,2.010,0,cif_files/mp-13089.cif
4,Pm-3m,221,5.0,0.0766,4.064437,4.064437,4.064437,90.000000,90.000000,90.000000,1.0,2.384,1,cif_files/mp-10732.cif

In [ ]:
# Encode categorical columns automatically

for col in df_data.select_dtypes(include="object").columns:
    if col != "cif":
        df_data[col] = df_data[col].astype("category").cat.codes

In [ ]:
#split data
train_df, temp_df = train_test_split(
    df_data,
    test_size=0.30,
    stratify=df_data["label"],
    random_state=42
)

val_df, test_df = train_test_split(
    temp_df,
    test_size=0.50,
    stratify=temp_df["label"],
    random_state=42
)

print("Train:", len(train_df))
print("Validation:", len(val_df))
print("Test:", len(test_df))

Train: 4900
Validation: 1050
Test: 1050

In [1]:
from pymatgen.io.cif import CifParser
import numpy as np
import torch
from torch_geometric.data import Data

# Example: build graph for a single CIF entry
entry = train_df.iloc[0]  # take first row of training data
cif_file = '/content/drive/MyDrive/Project' + entry['cif']
parser = CifParser(cif_files)
structure = parser.get_structures()[0]

# Node features: atomic number and electronegativity
atom_numbers = [site.specie.number for site in structure]
# Use Pettifor or Pauling electronegativity if available
atom_en = [site.specie.X if site.specie.X is not None else 0.0 for site in structure]
x = torch.tensor(list(zip(atom_numbers, atom_en)), dtype=torch.float)

# Positions (cartesian coordinates) for edge building
pos = torch.tensor(structure.cart_coords, dtype=torch.float)

# Compute edges by distance cutoff (e.g., 5 Å)
from torch_cluster import radius_graph
edge_index = radius_graph(pos, r=5.0, loop=False)
# Edge attributes: distances
row, col = edge_index
edge_attr = torch.norm(pos[row] - pos[col], dim=1, keepdim=True)

# Global (graph-level) features: spacegroup, number of atoms, band gap, lattice etc.
global_feat = torch.tensor([
    entry['spacegroup_number'], entry['number of atoms'], entry['Band Gap'],
    entry['a'], entry['b'], entry['c'],
    entry['alpha'], entry['beta'], entry['gamma'],
    entry['Z'], entry['electronegativity']
], dtype=torch.float).unsqueeze(0)  # shape [1, F]

data = Data(x=x, edge_index=edge_index, edge_attr=edge_attr, y=torch.tensor([entry['label']]),
            u=global_feat, batch=torch.tensor([0]*x.size(0)))
print(data)

ModuleNotFoundError: No module named 'pymatgen'

In [ ]:
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import CGConv, global_mean_pool

class CharlesCGCNN(nn.Module):
    def __init__(self, node_feat_dim=2, edge_feat_dim=1, hidden_dim=64, num_classes=2):
        super().__init__()
        # Two CGConv layers (input dims -> hidden -> hidden)
        self.conv1 = CGConv(channels=(node_feat_dim, hidden_dim), dim=edge_feat_dim)
        self.conv2 = CGConv(channels=(hidden_dim, hidden_dim), dim=edge_feat_dim)
        # Final linear layer (after concatenating global features)
        # We'll assume global feature vector length is 11 (as constructed above)
        self.fc = nn.Linear(hidden_dim + 11, num_classes)

    def forward(self, data):
        x, edge_index, edge_attr, batch, u = data.x, data.edge_index, data.edge_attr, data.batch, data.u
        x = self.conv1(x, edge_index, edge_attr)
        x = F.relu(x)
        x = self.conv2(x, edge_index, edge_attr)
        x = F.relu(x)
        # Pool atomic features into graph-level vector
        x = global_mean_pool(x, batch)  # shape [batch_size, hidden_dim]
        # Concatenate global attributes u
        out = torch.cat([x, u], dim=1)  # shape [batch_size, hidden_dim+11]
        out = self.fc(out)
        return out

# Instantiate the model
torch.manual_seed(42)
model = CharlesCGCNN(node_feat_dim=2, edge_feat_dim=1, hidden_dim=64, num_classes=2).to('cuda')
print(model)

In [ ]:
#convert cif to crystal structures
from pymatgen.analysis.local_env import CrystalNN

crystal_nn = CrystalNN()

def structure_to_graph(cif_path):

    structure = Structure.from_file(cif_path)

    node_features = []
    edge_index = []
    edge_attr = []

    for i, site in enumerate(structure):
        node_features.append([site.specie.Z])

    for i, site in enumerate(structure):

        neighbors = crystal_nn.get_nn_info(structure, i)

        for nbr in neighbors:

            j = nbr['site_index']
            dist = nbr['weight']

            edge_index.append([i, j])
            edge_attr.append([dist])

    x = torch.tensor(node_features, dtype=torch.float)
    edge_index = torch.tensor(edge_index).t().contiguous()
    edge_attr = torch.tensor(edge_attr, dtype=torch.float)

    return x, edge_index, edge_attr

In [ ]:
#Pytorch dataset class
class CrystalDataset(torch.utils.data.Dataset):

    def __init__(self, dataframe, cif_root):

        self.df = dataframe.reset_index(drop=True)
        self.cif_root = cif_root

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):

        row = self.df.iloc[idx]

        cif_path = os.path.join(self.cif_root, row["cif"])

        x, edge_index, edge_attr = structure_to_graph(cif_path)

        y = torch.tensor([row["label"]], dtype=torch.long)

        data = Data(
            x=x,
            edge_index=edge_index,
            edge_attr=edge_attr,
            y=y
        )

        return data

In [ ]:
#create dataloaders
cif_root = "/content/drive/MyDrive/Project"

train_dataset = CrystalDataset(train_df, cif_root)
val_dataset = CrystalDataset(val_df, cif_root)
test_dataset = CrystalDataset(test_df, cif_root)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32)
test_loader = DataLoader(test_dataset, batch_size=32)

In [ ]:
#CGNN Model
class CGCNN(nn.Module):

    def __init__(self):

        super().__init__()

        self.conv1 = CGConv(1, dim=32)
        self.conv2 = CGConv(32, dim=32)

        self.fc1 = nn.Linear(32, 64)
        self.fc2 = nn.Linear(64, 2)

    def forward(self, data):

        x, edge_index, edge_attr, batch = data.x, data.edge_index, data.edge_attr, data.batch

        x = F.relu(self.conv1(x, edge_index, edge_attr))
        x = F.relu(self.conv2(x, edge_index, edge_attr))

        x = global_mean_pool(x, batch)

        x = F.relu(self.fc1(x))
        x = self.fc2(x)

        return x

In [ ]:
#TRaining loop
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = CGCNN().to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

criterion = nn.CrossEntropyLoss()

def train():

    model.train()
    total_loss = 0

    for data in train_loader:

        data = data.to(device)

        optimizer.zero_grad()

        out = model(data)

        loss = criterion(out, data.y)

        loss.backward()

        optimizer.step()

        total_loss += loss.item()

    return total_loss / len(train_loader)

In [ ]:
#validation
def evaluate(loader):

    model.eval()

    preds = []
    labels = []

    with torch.no_grad():

        for data in loader:

            data = data.to(device)

            out = model(data)

            prob = torch.softmax(out, dim=1)[:,1]

            preds.extend(prob.cpu().numpy())
            labels.extend(data.y.cpu().numpy())

    preds_binary = np.array(preds) > 0.5

    acc = accuracy_score(labels, preds_binary)
    f1 = f1_score(labels, preds_binary)
    roc = roc_auc_score(labels, preds)

    print("Accuracy:", acc)
    print("F1:", f1)
    print("ROC-AUC:", roc)

    print(classification_report(labels, preds_binary))

In [ ]:
#Train Model
def train():

    model.train()
    total_loss = 0

    for data in train_loader:

        data = data.to(device)

        optimizer.zero_grad()

        out = model(data)

        loss = criterion(out, data.y.view(-1))

        loss.backward()

        optimizer.step()

        total_loss += loss.item()

    return total_loss / len(train_loader)

In [ ]:
import numpy as np
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report
)

def evaluate_model(loader, model):

    model.eval()

    all_probs = []
    all_preds = []
    all_labels = []

    with torch.no_grad():

        for data in loader:

            data = data.to(device)

            outputs = model(data)

            probs = torch.softmax(outputs, dim=1)[:,1]  # probability of class 1

            preds = torch.argmax(outputs, dim=1)

            all_probs.extend(probs.cpu().numpy())
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(data.y.view(-1).cpu().numpy())

    all_probs = np.array(all_probs)
    all_preds = np.array(all_preds)
    all_labels = np.array(all_labels)

    acc = accuracy_score(all_labels, all_preds)
    precision = precision_score(all_labels, all_preds)
    recall = recall_score(all_labels, all_preds)
    f1 = f1_score(all_labels, all_preds)
    roc = roc_auc_score(all_labels, all_probs)

    print("Accuracy:", round(acc,3))
    print("Precision:", round(precision,3))
    print("Recall:", round(recall,3))
    print("F1-score:", round(f1,3))
    print("ROC-AUC:", round(roc,3))

    print("\nClassification Report:\n")
    print(classification_report(all_labels, all_preds))

In [ ]:
print("Train Performance")
evaluate_model(train_loader, model)

In [ ]:
print("Validation Performance")
evaluate_model(val_loader, model)

In [ ]:
print("Test Performance")
evaluate_model(test_loader, model)

In [ ]:
from sklearn.metrics import roc_curve
import matplotlib.pyplot as plt

fpr, tpr, _ = roc_curve(all_labels, all_probs)

plt.plot(fpr, tpr)
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.show()

In [ ]:
Feature selection